# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbiter',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Mężczyzna'), ('F', 'Kobieta'), ('O', 'Inna')], default='O', max_length=1)),
                ('arbiter_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChessParty',
            fields=[
                ('chessparty_id', models.AutoField(primary_key=True, serialize=False)),
                ('arbiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chesseditor.Arbiter')),
            ],
        ),
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('chessman', models.CharField(choices=[('a1_w_rook', 'biała wieża a1'), ('h1_w_rook', 'biała wieża h1'), ('b1_w_knight', 'biały skoczek b1'), ('g1_w_knight', 'biały skoczek g1'), ('c1_w_bishop', 'biały goniec c1'), ('f1_w_bishop', 'biały goniec f1'), ('d1_w_queen', 'biały hetman d1'), ('e1_w_king', 'biały król e1'), ('a2_w_pawn', 'biały pion a2'), ('b2_w_pawn', 'biały pion b2'), ('c2_w_pawn', 'biały pion c2'), ('d2_w_pawn', 'biały pion d2'), ('e2_w_pawn', 'biały pion e2'), ('f2_w_pawn', 'biały pion f2'), ('g2_w_pawn', 'biały pion g2'), ('h2_w_pawn', 'biały pion h2'), ('a8_b_rook', 'czarna wieża a1'), ('h8_b_rook', 'czarna wieża h8'), ('b8_b_knight', 'czarny skoczek b1'), ('g8_b_knight', 'czarny skoczek g8'), ('c8_b_knight', 'czarny goniec c1'), ('f8_b_bishop', 'czarny goniec f8'), ('d8_b_queen', 'czarny hetman d1'), ('e8_b_king', 'czarny król e8'), ('a7_b_pawn', 'czarny pion a7'), ('b7_b_pawn', 'czarny pion b7'), ('c7_b_pawn', 'czarny pion c7'), ('d7_b_pawn', 'czarny pion d7'), ('e7_b_pawn', 'czarny pion e7'), ('f7_b_pawn', 'czarny pion f7'), ('g7_b_pawn', 'czarny pion g7'), ('h7_b_pawn', 'czarny pion h7')], default='pionek', max_length=30)),
                ('move', models.CharField(choices=[('a1', 'a1'), ('a2', 'a2'), ('a3', 'a3'), ('a4', 'a4'), ('a5', 'a5'), ('a6', 'a6'), ('a7', 'a7'), ('a8', 'a8'), ('b1', 'b1'), ('b2', 'b2'), ('b3', 'b3'), ('b4', 'b4'), ('b5', 'b5'), ('b6', 'b6'), ('b7', 'b7'), ('b8', 'b8'), ('c1', 'c1'), ('c2', 'c2'), ('c3', 'c3'), ('c4', 'c4'), ('c5', 'c5'), ('c6', 'c6'), ('c7', 'c7'), ('c8', 'c8'), ('d1', 'd1'), ('d2', 'd2'), ('d3', 'd3'), ('d4', 'd4'), ('d5', 'd5'), ('d6', 'd6'), ('d7', 'd7'), ('d8', 'd8'), ('e1', 'e1'), ('e2', 'e2'), ('e3', 'e3'), ('e4', 'e4'), ('e5', 'e5'), ('e6', 'e6'), ('e7', 'e7'), ('e8', 'e8'), ('f1', 'f1'), ('f2', 'f2'), ('f3', 'f3'), ('f4', 'f4'), ('f5', 'f5'), ('f6', 'f6'), ('f7', 'f7'), ('f8', 'f8'), ('g1', 'g1'), ('g2', 'g2'), ('g3', 'g3'), ('g4', 'g4'), ('g5', 'g5'), ('g6', 'g6'), ('g7', 'g7'), ('g8', 'g8'), ('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4'), ('h5', 'h5'), ('h6', 'h6'), ('h7', 'h7'), ('h8', 'h8')], default='a1', max_length=2)),
                ('move_id', models.AutoField(primary_key=True, serialize=False)),
                ('move_number', models.PositiveIntegerField(default=1)),
                ('party', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='chesseditor.ChessParty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('organizer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Mężczyzna'), ('F', 'Kobieta'), ('O', 'Inna')], default='O', max_length=1)),
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chessman', models.CharField(choices=[('a1_w_rook', 'biała wieża a1'), ('h1_w_rook', 'biała wieża h1'), ('b1_w_knight', 'biały skoczek b1'), ('g1_w_knight', 'biały skoczek g1'), ('c1_w_bishop', 'biały goniec c1'), ('f1_w_bishop', 'biały goniec f1'), ('d1_w_queen', 'biały hetman d1'), ('e1_w_king', 'biały król e1'), ('a2_w_pawn', 'biały pion a2'), ('b2_w_pawn', 'biały pion b2'), ('c2_w_pawn', 'biały pion c2'), ('d2_w_pawn', 'biały pion d2'), ('e2_w_pawn', 'biały pion e2'), ('f2_w_pawn', 'biały pion f2'), ('g2_w_pawn', 'biały pion g2'), ('h2_w_pawn', 'biały pion h2'), ('a8_b_rook', 'czarna wieża a1'), ('h8_b_rook', 'czarna wieża h8'), ('b8_b_knight', 'czarny skoczek b1'), ('g8_b_knight', 'czarny skoczek g8'), ('c8_b_knight', 'czarny goniec c1'), ('f8_b_bishop', 'czarny goniec f8'), ('d8_b_queen', 'czarny hetman d1'), ('e8_b_king', 'czarny król e8'), ('a7_b_pawn', 'czarny pion a7'), ('b7_b_pawn', 'czarny pion b7'), ('c7_b_pawn', 'czarny pion c7'), ('d7_b_pawn', 'czarny pion d7'), ('e7_b_pawn', 'czarny pion e7'), ('f7_b_pawn', 'czarny pion f7'), ('g7_b_pawn', 'czarny pion g7'), ('h7_b_pawn', 'czarny pion h7')], default='pionek', max_length=30)),
                ('move', models.CharField(choices=[('a1', 'a1'), ('a2', 'a2'), ('a3', 'a3'), ('a4', 'a4'), ('a5', 'a5'), ('a6', 'a6'), ('a7', 'a7'), ('a8', 'a8'), ('b1', 'b1'), ('b2', 'b2'), ('b3', 'b3'), ('b4', 'b4'), ('b5', 'b5'), ('b6', 'b6'), ('b7', 'b7'), ('b8', 'b8'), ('c1', 'c1'), ('c2', 'c2'), ('c3', 'c3'), ('c4', 'c4'), ('c5', 'c5'), ('c6', 'c6'), ('c7', 'c7'), ('c8', 'c8'), ('d1', 'd1'), ('d2', 'd2'), ('d3', 'd3'), ('d4', 'd4'), ('d5', 'd5'), ('d6', 'd6'), ('d7', 'd7'), ('d8', 'd8'), ('e1', 'e1'), ('e2', 'e2'), ('e3', 'e3'), ('e4', 'e4'), ('e5', 'e5'), ('e6', 'e6'), ('e7', 'e7'), ('e8', 'e8'), ('f1', 'f1'), ('f2', 'f2'), ('f3', 'f3'), ('f4', 'f4'), ('f5', 'f5'), ('f6', 'f6'), ('f7', 'f7'), ('f8', 'f8'), ('g1', 'g1'), ('g2', 'g2'), ('g3', 'g3'), ('g4', 'g4'), ('g5', 'g5'), ('g6', 'g6'), ('g7', 'g7'), ('g8', 'g8'), ('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4'), ('h5', 'h5'), ('h6', 'h6'), ('h7', 'h7'), ('h8', 'h8')], default='a1', max_length=2)),
                ('state_id', models.PositiveIntegerField(default=0)),
                ('is_capture', models.CharField(choices=[('true', 'zbity'), ('false', 'nie zbity')], default='false', max_length=9)),
                ('party', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='chesseditor.ChessParty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_tournament', models.CharField(max_length=50)),
                ('date_of_start', models.DateField()),
                ('date_of_end', models.DateField()),
                ('place_of_tournament', models.CharField(max_length=50)),
                ('max_nb_of_players', models.IntegerField(default=50)),
            ],
        ),
        migrations.AddField(
            model_name='organizer',
            name='tournament',
            field=models.ManyToManyField(to='chesseditor.Tournament'),
        ),
        migrations.AddField(
            model_name='chessparty',
            name='black',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='something_black', to='chesseditor.Player'),
        ),
        migrations.AddField(
            model_name='chessparty',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chesseditor.Tournament'),
        ),
        migrations.AddField(
            model_name='chessparty',
            name='white',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='something_white', to='chesseditor.Player'),
        ),
    ]
