# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbiter',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Mężczyzna'), ('F', 'Kobieta'), ('O', 'Inna')], default='O', max_length=1)),
                ('arbiter', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChessParty',
            fields=[
                ('chessparty', models.AutoField(primary_key=True, serialize=False)),
                ('arbiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chesseditor.Arbiter')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id_move', models.AutoField(primary_key=True, serialize=False)),
                ('move_number', models.IntegerField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chesseditor.ChessParty')),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id_organizer', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Mężczyzna'), ('F', 'Kobieta'), ('O', 'Inna')], default='O', max_length=1)),
                ('player', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_tournament', models.CharField(max_length=50)),
                ('date_of_start', models.DateField()),
                ('date_of_end', models.DateField()),
                ('place_of_tournament', models.CharField(max_length=50)),
                ('max_nb_of_players', models.IntegerField(default=50)),
            ],
        ),
        migrations.AddField(
            model_name='organizer',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chesseditor.Tournament'),
        ),
        migrations.AddField(
            model_name='chessparty',
            name='black',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='something_black', to='chesseditor.Player'),
        ),
        migrations.AddField(
            model_name='chessparty',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chesseditor.Tournament'),
        ),
        migrations.AddField(
            model_name='chessparty',
            name='white',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='something_white', to='chesseditor.Player'),
        ),
    ]
