# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chesseditor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moves',
            name='party',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.CASCADE, to='chesseditor.ChessParty', verbose_name='Partia'),
        ),
        migrations.AlterField(
            model_name='state',
            name='party',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.CASCADE, to='chesseditor.ChessParty', verbose_name='Partia'),
        ),
    ]
