# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chesseditor', '0002_move_move'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arbiter',
            old_name='arbiter',
            new_name='arbiter_id',
        ),
        migrations.RenameField(
            model_name='chessparty',
            old_name='chessparty',
            new_name='chessparty_id',
        ),
        migrations.RenameField(
            model_name='move',
            old_name='id_move',
            new_name='move_id',
        ),
        migrations.RenameField(
            model_name='organizer',
            old_name='id_organizer',
            new_name='organizer_id',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player',
            new_name='player_id',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='tournament',
            new_name='tournament_id',
        ),
    ]
