# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chesseditor', '0002_state_is_capture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='is_capture',
            field=models.CharField(choices=[('true', 'zbity'), ('false', 'nie zbity')], default='false', max_length=9),
        ),
    ]
