# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chesseditor', '0004_move_chessman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='chessman',
            field=models.CharField(choices=[('WKing', 'Biały Król'), ('WHetman', 'Biała Królowa'), ('WRock', 'Biała Wieża'), ('WKnight', 'Biały skoczek'), ('pionek', 'pionek'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała')], default='pionek', max_length=20),
        ),
    ]
