# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chesseditor', '0006_auto_20170524_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='move_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
