# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chesseditor', '0007_auto_20170524_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='chessman',
            field=models.CharField(choices=[('a2_w_pawn', 'biały pionek a2'), ('b2_w_pawn', 'pionek b2'), ('c2_w_pawn', 'pionek c2'), ('d2_white_pawn', 'pionek d2'), ('e2_white_pawn', 'pionek e2'), ('f2_white_pawn', 'pionek f2'), ('g2_white_pawn', 'pionek g2'), ('h2_white_pawn', 'pionek h2'), ('a7_white_pawn', 'pionek a7'), ('b7_white_pawn', 'pionek b7'), ('c7_white_pawn', 'pionek c7'), ('d7_white_pawn', 'pionek d7'), ('e7_white_pawn', 'pionek e7'), ('f7_white_pawn', 'pionek f7'), ('g7_white_pawn', 'pionek g7'), ('h7_white_pawn', 'pionek h7'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała Królowa'), ('WHetman', 'Biała')], default='pionek', max_length=20),
        ),
    ]
