# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chesseditor', '0010_auto_20170529_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('states_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='chesseditor.States')),
                ('move_id', models.AutoField(primary_key=True, serialize=False)),
                ('move_number', models.PositiveIntegerField(default=1)),
            ],
            bases=('chesseditor.states',),
        ),
        migrations.RemoveField(
            model_name='move',
            name='party',
        ),
        migrations.DeleteModel(
            name='Move',
        ),
    ]
