# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chesseditor', '0011_auto_20170529_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moves',
            name='states_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='chesseditor.States'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
