# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chesseditor', '0016_auto_20170623_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moves',
            name='chessman',
            field=models.CharField(choices=[('biała wieża a1', '&#9814;'), ('&#9814;', 'biała wieża h1'), ('&#9816;', 'biały skoczek b1'), ('&#9816;', 'biały skoczek g1'), ('&#9815;', 'biały goniec c1'), ('&#9815;', 'biały goniec f1'), ('&#9813;', 'biały hetman d1'), ('&#9812;', 'biały król e1'), ('&#9817;', 'biały pion a2'), ('&#9817;', 'biały pion b2'), ('&#9817;', 'biały pion c2'), ('&#9817;', 'biały pion d2'), ('&#9817;', 'biały pion e2'), ('&#9817;', 'biały pion f2'), ('&#9817;', 'biały pion g2'), ('&#9817;', 'biały pion h2'), ('&#9820;', 'czarna wieża a8'), ('&#9820;', 'czarna wieża h8'), ('&#9822;', 'czarny skoczek b8'), ('&#9822;', 'czarny skoczek g8'), ('&#9821;', 'czarny goniec c8'), ('&#9821;', 'czarny goniec f8'), ('&#9813;', 'czarny hetman d8'), ('&#9818;', 'czarny król e8'), ('&#9823;', 'czarny pion a7'), ('&#9823;', 'czarny pion b7'), ('&#9823;', 'czarny pion c7'), ('&#9823;', 'czarny pion d7'), ('&#9823;', 'czarny pion e7'), ('&#9823;', 'czarny pion f7'), ('&#9823;7', 'czarny pion g7'), ('&#9823;', 'czarny pion h7')], default='pionek', max_length=30, verbose_name='Figura Szachowa'),
        ),
        migrations.AlterField(
            model_name='state',
            name='chessman',
            field=models.CharField(choices=[('biała wieża a1', '&#9814;'), ('&#9814;', 'biała wieża h1'), ('&#9816;', 'biały skoczek b1'), ('&#9816;', 'biały skoczek g1'), ('&#9815;', 'biały goniec c1'), ('&#9815;', 'biały goniec f1'), ('&#9813;', 'biały hetman d1'), ('&#9812;', 'biały król e1'), ('&#9817;', 'biały pion a2'), ('&#9817;', 'biały pion b2'), ('&#9817;', 'biały pion c2'), ('&#9817;', 'biały pion d2'), ('&#9817;', 'biały pion e2'), ('&#9817;', 'biały pion f2'), ('&#9817;', 'biały pion g2'), ('&#9817;', 'biały pion h2'), ('&#9820;', 'czarna wieża a8'), ('&#9820;', 'czarna wieża h8'), ('&#9822;', 'czarny skoczek b8'), ('&#9822;', 'czarny skoczek g8'), ('&#9821;', 'czarny goniec c8'), ('&#9821;', 'czarny goniec f8'), ('&#9813;', 'czarny hetman d8'), ('&#9818;', 'czarny król e8'), ('&#9823;', 'czarny pion a7'), ('&#9823;', 'czarny pion b7'), ('&#9823;', 'czarny pion c7'), ('&#9823;', 'czarny pion d7'), ('&#9823;', 'czarny pion e7'), ('&#9823;', 'czarny pion f7'), ('&#9823;7', 'czarny pion g7'), ('&#9823;', 'czarny pion h7')], default='pionek', max_length=30, verbose_name='Figura Szachowa'),
        ),
    ]
