# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chesseditor', '0018_auto_20170626_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Stan', 'verbose_name_plural': 'Aktualny Stan Parti'},
        ),
    ]
